blank_issues_enabled: false
contact_links:
    - name: Ask a Question
      url: https://github.com/spatie/laravel-medialibrary-pro/issues/new
      about: Ask for help
    - name: Feature Request
      url: https://github.com/spatie/laravel-medialibrary-pro/issues/new
      about: Share ideas for new features
